### ISSUE TITLE
Unable to use event put-bucket-notification-configuration

### ISSUE THREAD

**Issue by jackthecodemonkey** [ar90n/serverless-s3-local#98]
Hi,
I tried to hook S3 up with SQS queue by running a command
```
awslocal --endpoint-url=http://localhost:8000 s3api put-bucket-notification-configuration --bucket local-bucket --notification-configuration file://lead.json --profile s3local --region us-east-1
```

and my lead.json
```
{
    "QueueConfigurations": [
        {
            "QueueArn": "arn:aws:sqs:us-east-1:000000000000:lead",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}
```

The error message I got
```
An error occurred (NotImplemented) when calling the PutBucketNotificationConfiguration operation: A parameter you provided implies functionality that is not implemented
```

If I replace `http://localhost:8000` with a S3 server generated by localstack. 
it works fine but I would like to use this plugin instead of localstack.

Any ideas or did I miss something?
Thanks!

**Comment by ar90n** [comment]
Hi @jackthecodemonkey 
Thanks for your comment! Unfortunately, serverless-s3-local doesn't support integration with SQS. Because it seems that s3rver which is our backend system doesn't support it. 

In my opinion, you can write a simple lambda function to relay the S3 event to SQS as a workaround. I'm truly sorry for not being able to help you.
